"""add replay flags to runs

Revision ID: a3a7ad9b6720
Revises: fdbf6cd6d250
Create Date: 2026-09-03 15:46:40.235759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a7ad9b6720'
down_revision: Union[str, Sequence[str], None] = 'fdbf6cd6d250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('replay_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('runs', sa.Column('base_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'base_url')
    op.drop_column('runs', 'replay_enabled')
    # ### end Alembic commands ###
